// inspired from https://github.com/eslint-stylistic/eslint-stylistic/blob/main/packages/eslint-plugin/configs/customize.ts

/** @type {import('eslint').Linter.Config} */
module.exports = {
  root: true,
  env: {
    node: true,
  },
  extends: [
    'eslint:recommended',
  ],
  rules: {
    'array-bracket-spacing': ['error', 'never'],
    'arrow-body-style': ['error', 'as-needed'],
    'arrow-parens': ['error', 'as-needed'],
    'arrow-spacing': ['error', { after: true, before: true }],
    'brace-style': ['error', '1tbs', { allowSingleLine: true }],
    'comma-dangle': ['error', 'always-multiline'],
    'comma-spacing': ['error', { after: true, before: false }],
    'comma-style': ['error', 'last'],
    'dot-location': ['error', 'property'],
    'eol-last': 'error',
    'func-style': ['error', 'expression', {
      allowArrowFunctions: true,
    }],
    'indent': ['error', 2, {
      ArrayExpression: 1,
      CallExpression: { arguments: 1 },
      flatTernaryExpressions: false,
      FunctionDeclaration: { body: 1, parameters: 1 },
      FunctionExpression: { body: 1, parameters: 1 },
      ignoreComments: false,
      ignoredNodes: [
        'FunctionExpression > .params[decorators.length > 0]',
        'FunctionExpression > .params > :matches(Decorator, :not(:first-child))',
      ],
      ImportDeclaration: 1,
      MemberExpression: 1,
      ObjectExpression: 1,
      outerIIFEBody: 1,
      SwitchCase: 1,
      VariableDeclarator: 1,
    }],
    'keyword-spacing': ['error'],
    'max-len': ['error', {
      code: 160,
      ignoreStrings:true,
      ignoreTemplateLiterals: true,
      ignoreRegExpLiterals: true,
    }],
    'multiline-ternary': ['error', 'always-multiline'],
    'new-parens': 'error',
    'no-duplicate-imports': 'error',
    'no-else-return': 'error',
    'no-extra-parens': ['error', 'functions'],
    'no-floating-decimal': 'error',
    'no-lonely-if': 'error',
    'no-mixed-operators': ['error', {
      allowSamePrecedence: true,
      groups: [
        ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
        ['&&', '||'],
        ['in', 'instanceof'],
      ],
    }],
    'no-nested-ternary': 'warn',
    'no-tabs': 'error',
    'no-template-curly-in-string': 'warn',
    'no-throw-literal': 'error',
    'no-trailing-spaces': 'error',
    'no-unreachable-loop': 'warn',
    'no-useless-rename': 'error',
    'no-unused-expressions': 'warn',
    'no-var': 'warn',
    'no-whitespace-before-property': 'error',
    'object-curly-spacing': ['error', 'always', { arraysInObjects: false, objectsInObjects: false }],
    'object-shorthand': 'warn',
    'padded-blocks': ['error', { blocks: 'never', classes: 'always', switches: 'never' }],
    'prefer-const': 'warn',
    'semi': 'error',
    'semi-spacing': ['error', { after: true, before: false }],
    'spaced-comment': ['error', 'always', {
      block: {
        balanced: true,
        exceptions: ['*'],
        markers: ['!'],
      },
      line: {
        exceptions: ['/', '#'],
        markers: ['/'],
      },
    }],
    'template-curly-spacing': 'error',
    'template-tag-spacing': ['error', 'never'],
    'yield-star-spacing': ['error', { after: true, before: false }],
    'yoda': ['warn', 'never'],
  },
};
